api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        ApiPlatform\Core\Exception\InvalidArgumentException: 'HTTP_BAD_REQUEST'
        App\Exception\UserNotFoundException: 404
    collection:
        pagination:
            items_per_page: 40

framework:
    serializer: { enable_annotations: true }