#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

api_login:
    path: /api/token

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
